{% set version = "2.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nlmixr2est
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nlmixr2est_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nlmixr2est/nlmixr2est_{{ version }}.tar.gz
  sha256: f5ebeec352cf327b9e001420832670dfe873b3d87bb1ae0d9c9384145a81a6a8

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
    - '*/Rblas.dll'       # [win]
    - '*/Rlapack.dll'     # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-backports
    - r-bh
    - r-checkmate
    - r-cli
    - r-knitr
    - r-lbfgsb3c
    - r-lotri
    - r-magrittr
    - r-matrix
    - r-minpack.lm
    - r-minqa
    - r-n1qn1 >=6.0.1_10
    - r-nlme
    - r-nlmixr2data
    - r-rcpp
    - r-rcpparmadillo >=0.11.2.3.1
    - r-rex
    - r-rxode2 >=2.1.0
    - r-rxode2parse >=2.0.11
    - r-rxode2random >=2.0.9
    - r-symengine
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs           # [win]
    - {{ native }}libwinpthread-git  # [win]
    - r-backports
    - r-checkmate
    - r-cli
    - r-knitr
    - r-lbfgsb3c
    - r-lotri
    - r-magrittr
    - r-matrix
    - r-minpack.lm
    - r-minqa
    - r-n1qn1 >=6.0.1_10
    - r-nlme
    - r-nlmixr2data
    - r-rcpp
    - r-rcpparmadillo >=0.11.2.3.1
    - r-rex
    - r-rxode2 >=2.1.0
    - r-rxode2parse >=2.0.11
    - r-rxode2random >=2.0.9
    - r-symengine

test:
  commands:
    - $R -e "library('nlmixr2est')"           # [not win]
    - "\"%R%\" -e \"library('nlmixr2est')\""  # [win]

about:
  home: https://github.com/nlmixr2/nlmixr2est
  dev_url: https://nlmixr2.github.io/nlmixr2est/
  license: GPL-3.0-or-later
  summary: Fit and compare nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential equation solving is by compiled C code provided in the 'rxode2'
    package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: nlmixr2est
# Title: Nonlinear Mixed Effects Models in Population PK/PD, Estimation Routines
# Version: 2.1.8
# Authors@R: c( person("Matthew", "Fidler", , "matt.fidler@novartis.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-8538-6691")), person("Yuan", "Xiong", , "yuan.xiong@gmail.com", role = "aut"), person("Rik", "Schoemaker", , "rik.schoemaker@occams.com", role = "aut", comment = c(ORCID = "0000-0002-7538-3005")), person("Justin", "Wilkins", , "justin.wilkins@occams.com", role = "aut", comment = c(ORCID = "0000-0002-7099-9396")), person("Wenping", "Wang", , "wwang8198@gmail.com", role = "aut"), person("Robert", "Leary", role = "ctb"), person("Mason", "McComb", , "mason.c.mccomb@gmail.com", role = "ctb", comment = c(ORCID = "0000-0001-9871-8616")), person("Vipul", "Mann", , "vm2583@columbia.edu", role = "aut"), person("Mirjam", "Trame", , "mirjam.trame@gmail.com", role = "ctb"), person("Mahmoud", "Abdelwahab", , "mah.tareq87@gmail.com", role = "ctb"), person("Teun", "Post", , "t.post@lapp.nl", role = "ctb"), person("Richard", "Hooijmaijers", , "richardhooijmaijers@gmail.com", role = "aut"), person("Hadley", "Wickham", role = "ctb"), person("Dirk", "Eddelbuettel", , "edd@debian.org", role = "cph"), person("Johannes", "Pfeifer", role = "ctb"), person("Robert B.", "Schnabel", role = "ctb"), person("Elizabeth", "Eskow", role = "ctb"), person("Emmanuelle", "Comets", , "emmanuelle.comets@inserm.fr", role = "ctb"), person("Audrey", "Lavenu", role = "ctb"), person("Marc", "Lavielle", role = "ctb"), person("David", "Ardia", role = "cph"), person("Katharine", "Mullen", role = "cph"), person("Ben", "Goodrich", role = "ctb") )
# Maintainer: Matthew Fidler <matt.fidler@novartis.com>
# Description: Fit and compare nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential equation solving is by compiled C code provided in the 'rxode2' package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>).
# License: GPL (>= 3)
# URL: https://github.com/nlmixr2/nlmixr2est, https://nlmixr2.github.io/nlmixr2est/
# Depends: nlmixr2data, R (>= 4.0)
# Imports: backports, checkmate, cli, graphics, knitr, lbfgsb3c, lotri, magrittr, Matrix, methods, minqa, n1qn1 (>= 6.0.1-10), nlme, Rcpp, rex, rxode2 (>= 2.0.12), stats, symengine, utils
# Suggests: broom.mixed, crayon, data.table, devtools, digest, dplyr (>= 1.1.0), generics, nloptr, qs, sys, testthat, tibble, withr, xgxr, sfsmisc, rxode2parse (>= 2.0.11), rxode2random (>= 2.0.9)
# LinkingTo: BH, lbfgsb3c, Rcpp, RcppArmadillo (>= 0.11.2.3.1), rxode2 (>= 2.0.12), rxode2parse (>= 2.0.11), rxode2random (>= 2.0.9)
# Biarch: true
# Config/testthat/edition: 3
# Encoding: UTF-8
# Language: en-US
# NeedsCompilation: yes
# RoxygenNote: 7.2.3
# LazyData: true
# Packaged: 2023-10-08 03:07:25 UTC; matt
# Author: Matthew Fidler [aut, cre] (<https://orcid.org/0000-0001-8538-6691>), Yuan Xiong [aut], Rik Schoemaker [aut] (<https://orcid.org/0000-0002-7538-3005>), Justin Wilkins [aut] (<https://orcid.org/0000-0002-7099-9396>), Wenping Wang [aut], Robert Leary [ctb], Mason McComb [ctb] (<https://orcid.org/0000-0001-9871-8616>), Vipul Mann [aut], Mirjam Trame [ctb], Mahmoud Abdelwahab [ctb], Teun Post [ctb], Richard Hooijmaijers [aut], Hadley Wickham [ctb], Dirk Eddelbuettel [cph], Johannes Pfeifer [ctb], Robert B. Schnabel [ctb], Elizabeth Eskow [ctb], Emmanuelle Comets [ctb], Audrey Lavenu [ctb], Marc Lavielle [ctb], David Ardia [cph], Katharine Mullen [cph], Ben Goodrich [ctb]
# Repository: CRAN
# Date/Publication: 2023-10-08 04:40:03 UTC
